REVIEW_UI_HTML = r"""<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link rel="icon" href="data:,">
  <title>VIE 人工复核</title>
  <style>
    :root{font-family:Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#172033;background:#f4f6f9}
    *{box-sizing:border-box}body{margin:0}.top{height:64px;background:#111827;color:#fff;display:flex;align-items:center;gap:18px;padding:0 24px}.top strong{font-size:18px}.top span{color:#aeb8c9;font-size:13px}.layout{display:grid;grid-template-columns:320px minmax(380px,1fr) 430px;min-height:calc(100vh - 64px)}
    .queue,.review{background:#fff;padding:20px;overflow:auto}.queue{border-right:1px solid #dde2ea}.review{border-left:1px solid #dde2ea}.source{padding:22px;overflow:auto}.toolbar{display:flex;gap:8px;margin-bottom:15px}.toolbar input,.toolbar select,.review input,.review textarea,.review select{width:100%;border:1px solid #c8d0dc;border-radius:8px;padding:10px;font:inherit}.toolbar button,.review button{border:0;border-radius:8px;padding:10px 14px;font-weight:650;cursor:pointer;white-space:nowrap;min-width:64px}.primary{background:#1d4ed8;color:#fff}.reject{background:#fff1f2;color:#be123c;border:1px solid #fecdd3!important}.discard{background:#fff7ed;color:#9a3412;border:1px solid #fed7aa!important}.queue-count{font-size:13px;color:#667085;margin:0 0 10px}.task{padding:13px;border:1px solid #e0e5ec;border-radius:10px;margin:8px 0;cursor:pointer}.task.active{border-color:#2563eb;background:#eff6ff}.task small{display:block;color:#667085;margin-top:5px}.pill{display:inline-block;background:#fff4d6;color:#8a5b00;border-radius:999px;padding:3px 8px;font-size:12px}.candidate{border:1px solid #bfdbfe!important;background:#eff6ff;color:#1d4ed8;margin:0 6px 6px 0;padding:6px 9px!important;font-size:12px}.image-wrap{position:relative;display:inline-block;max-width:100%;box-shadow:0 8px 30px #1f293720;background:#fff}.image-wrap img{display:block;max-width:100%;height:auto}.bbox{position:absolute;border:3px solid #ef4444;background:#ef444425;pointer-events:none}.empty{color:#667085;padding:35px 10px;text-align:center}.field{margin:16px 0}.field label{display:block;font-size:12px;font-weight:700;color:#475467;margin-bottom:6px;text-transform:uppercase;letter-spacing:.04em}.evidence{white-space:pre-wrap;background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:12px;max-height:210px;overflow:auto;font-size:13px}.meta{display:grid;grid-template-columns:1fr 1fr;gap:8px;font-size:13px;color:#475467}.actions{display:flex;gap:10px;flex-wrap:wrap}.notice{padding:10px;border-radius:8px;margin:10px 0;font-size:13px}.error{background:#fff1f2;color:#9f1239}.ok{background:#ecfdf3;color:#166534}@media(max-width:1050px){.layout{grid-template-columns:280px 1fr}.review{grid-column:1/-1;border-left:0;border-top:1px solid #dde2ea}}@media(max-width:700px){.layout{display:block}.queue{max-height:46vh}.queue,.review{border:0;border-bottom:1px solid #dde2ea}.source{min-height:300px}}
  </style>
</head>
<body>
  <header class="top"><strong>Vocabulary Ingestion Engine</strong><span>人工复核 · 原页与机器结果对照</span></header>
  <main class="layout">
    <aside class="queue">
      <form class="toolbar" id="accessForm"><input id="token" type="password" autocomplete="new-password" placeholder="API 密钥"><button class="primary" id="connect" type="submit">连接</button></form>
      <div class="toolbar"><select id="status"><option>OPEN</option><option>IN_PROGRESS</option><option>ESCALATED</option></select><button id="refresh">刷新</button></div>
      <div class="queue-count" id="queueCount"></div>
      <div id="queue"><div class="empty">输入 API 密钥后载入待复核项</div></div>
    </aside>
    <section class="source"><div id="source"><div class="empty">选择一项查看原始页面</div></div></section>
    <aside class="review">
      <div id="message"></div><div id="detail"><div class="empty">选择一项开始复核</div></div>
    </aside>
  </main>
  <script>
    const state={token:sessionStorage.getItem('vieToken')||'',items:[],current:null};
    const $=id=>document.getElementById(id); $('token').value=state.token;
    async function api(path,options={}){const headers={...(options.headers||{}),Authorization:`Bearer ${state.token}`};if(options.body)headers['Content-Type']='application/json';const r=await fetch(path,{...options,headers});if(!r.ok){let body={};try{body=await r.json()}catch{}throw new Error(body.detail||`请求失败 (${r.status})`)}return r}
    function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
    function reasonLabel(value){return ({G4_VALIDATION_FAILED:'字段校验失败',LOW_OCR_CONFIDENCE:'OCR 置信度低',STRUCTURED_EXTRACTION_UNCERTAIN:'结构化结果待确认',NO_TEXT_LAYER:'无文本层页面',MANUAL_QA:'人工抽检'})[value]||value.replaceAll('_',' ')}
    function message(text,type='ok'){$('message').innerHTML=text?`<div class="notice ${type}">${esc(text)}</div>`:''}
    async function loadQueue(){message('');try{const r=await api(`/api/v1/reviews?status=${encodeURIComponent($('status').value)}&limit=200`);const data=await r.json();state.items=data.items;$('queueCount').textContent=data.returned_count===data.count?`${data.count} 项待处理`:`显示最新 ${data.returned_count} 项，共 ${data.count} 项待处理`;$('queue').innerHTML=data.items.length?data.items.map(item=>`<div class="task ${state.current?.id===item.id?'active':''}" data-id="${item.id}"><span class="pill">${esc(reasonLabel(item.reason_code))}</span><strong style="display:block;margin-top:7px">${esc(item.current_value||item.target_entity_type)}</strong><small>第 ${esc(item.page?.page_number||'—')} 页 · ${esc(item.target_field_path||item.target_entity_type)}</small></div>`).join(''):'<div class="empty">当前没有待复核项</div>';$('queue').querySelectorAll('.task').forEach(el=>el.onclick=()=>selectTask(el.dataset.id))}catch(e){message(e.message,'error')}}
    async function selectTask(id){try{const r=await api(`/api/v1/reviews/${id}`);state.current=await r.json();renderDetail();loadQueue();if(window.innerWidth<=700)$('source').scrollIntoView({behavior:'smooth'})}catch(e){message(e.message,'error')}}
    function renderSource(item){if(!item.page){$('source').innerHTML='<div class="empty">此任务没有关联页图</div>';return}const box=item.bbox||{};let overlay='';if(box.unit==='normalized'){overlay=`<div class="bbox" style="left:${box.x1*100}%;top:${box.y1*100}%;width:${(box.x2-box.x1)*100}%;height:${(box.y2-box.y1)*100}%"></div>`}$('source').innerHTML=`<h3>原始页 · ${esc(item.page.page_number)}</h3><div class="image-wrap"><img id="pageImage" alt="原始页 ${esc(item.page.page_number)}">${overlay}</div>`;fetch(item.page.image_url,{headers:{Authorization:`Bearer ${state.token}`}}).then(r=>{if(!r.ok)throw new Error('页图载入失败');return r.blob()}).then(blob=>$('pageImage').src=URL.createObjectURL(blob)).catch(e=>message(e.message,'error'))}
    function renderDetail(){const i=state.current;renderSource(i);let edit='';if(i.target_entity_type==='VocabularyEntry')edit=`<div class="field"><label>词条</label><input id="correction" value="${esc(i.current_value)}"></div>`;else if(i.target_entity_type==='SourceBlock')edit=`<div class="field"><label>校正文本</label><textarea id="correction" rows="6">${esc(i.current_value)}</textarea></div>`;else edit=`<div class="field"><label>页面分类</label><select id="correction"><option value="NON_TEXT_PAGE">非文本页</option></select></div>`;const candidates=(i.candidate_values||[]).filter(value=>typeof value==='string');const candidateHtml=candidates.length?`<div class="field"><label>候选值</label>${candidates.map((value,index)=>`<button class="candidate" data-candidate="${index}">${esc(value)}</button>`).join('')}</div>`:'';const discard=i.target_entity_type==='SourceBlock'?'<button class="discard" id="discard">标记为非文本噪声</button>':'';$('detail').innerHTML=`<h2 style="margin-top:0">${esc(reasonLabel(i.reason_code))}</h2><div class="meta"><span>目标：${esc(i.target_entity_type)}</span><span>置信度：${i.confidence==null?'—':Number(i.confidence).toFixed(3)}</span><span>字段：${esc(i.target_field_path||'—')}</span><span>状态：${esc(i.status)}</span></div><div class="field"><label>来源证据</label><div class="evidence">${esc(i.source_text||JSON.stringify(i.source_context,null,2))}</div></div>${edit}${candidateHtml}<div class="field"><label>复核人</label><input id="reviewer" autocomplete="name" placeholder="真实姓名或工号" value="${esc(sessionStorage.getItem('vieReviewer')||'')}"></div><div class="field"><label>备注</label><textarea id="notes" rows="3" placeholder="只需记录必要说明"></textarea></div><div class="actions"><button class="primary" id="accept">确认并下一项</button>${discard}<button class="reject" id="reject">退回 / 升级</button></div>`;$('detail').querySelectorAll('.candidate').forEach(button=>button.onclick=()=>{$('correction').value=candidates[Number(button.dataset.candidate)]});$('accept').onclick=()=>resolve('ACCEPT');$('reject').onclick=()=>resolve('REJECT');if($('discard'))$('discard').onclick=()=>resolve('DISCARD')}
    async function resolve(decision){const i=state.current,reviewer=$('reviewer').value.trim();if(!reviewer){message('请填写真实复核人。','error');return}sessionStorage.setItem('vieReviewer',reviewer);const body={reviewer_id:reviewer,decision,notes:$('notes').value.trim()};const value=$('correction').value;if(i.target_entity_type==='VocabularyEntry')body.lemma=value;else if(i.target_entity_type==='SourceBlock'&&decision!=='DISCARD')body.corrected_text=value;else if(i.target_entity_type!=='SourceBlock')body.classification=value;try{await api(`/api/v1/reviews/${i.id}/resolve`,{method:'POST',body:JSON.stringify(body)});message('已保存人工审计记录。');state.current=null;$('detail').innerHTML='<div class="empty">已完成，选择下一项</div>';$('source').innerHTML='<div class="empty">选择下一项查看原始页面</div>';await loadQueue();if(state.items[0])selectTask(state.items[0].id)}catch(e){message(e.message,'error')}}
    $('accessForm').onsubmit=event=>{event.preventDefault();state.token=$('token').value.trim();sessionStorage.setItem('vieToken',state.token);loadQueue()};$('refresh').onclick=loadQueue;$('status').onchange=loadQueue;if(state.token)loadQueue();
  </script>
</body>
</html>"""
